version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: userapi_sqlserver
    ports:
      - "1435:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "LojaProdutoApp@2025"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:latest
    container_name: userapi_rabbitmq
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped
